### PR TITLE
GPII-3958: Adjust gpii-app to work with the new PSPChannel API.

### PR DESCRIPTION
**Pull request by cindyli**
With [the change of PSPChannel API](https://github.com/GPII/universal/pull/826) being merged into the universal repo, gpii-app stops working with the universal master. 

PSPChannel now expects a slightly different incoming message while PSPChannel output messages stay unchanged. The PSPChannel API is [here](https://github.com/GPII/universal/blob/master/documentation/PSPChannel.md).

This pull request adjusts gpii-app to work with the new API. @Karadaliev or @krisYanachkov, I'm not sure if it covers all messages sent to PSPChannel (Local flow manager). Please have a look. Thanks.

Please don't merge this pull request directly since it is pointing to my own gpii/windows branch which pulls in the universal master branch.

### CODE REVIEW

**Comment by Karadaliev** [comment]
Hey @cindyli thank you for the notice. We will try to get to this task ASAP! 🛩

**Comment by amb26** [comment]
Failure:
````
12:50:31.549:  jq: FAIL: Module "gpii.tests.dev.config tests" Test name "GPII application dev config integration tests" - Message: Tray tooltip label - at sequence position 7 of 16
12:50:31.549:  jq: Expected: Morphic: User Signed In
12:50:31.549:  jq: Actual: Morphic: Ready
````
Note that this failure was also observed with https://github.com/GPII/gpii-app/pull/176 - is this a race condition that is possibly in master already? Great if you could take a look, thanks @Karadaliev - cheers!

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
CI claimed that "VM is locked" - ok to test

**Comment by amb26** [comment]
````
App threw an error during load
Error: Cannot find module 'gpii-windows/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (V:\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
````
Looks like we have some significant form of build problem ....

**Comment by amb26** [comment]
Perhaps the famous miraculous disappearance of the 4.5.1 .NET SDK?
````
ResolveAssemblyReferences:
  Primary reference "mscorlib".
      Could not find dependent files. Expected file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll" does not exist.
      Resolved file path is "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll".
````

**Comment by cindyli** [comment]
Updated "cindyli/windows#GPII-3958" dependency to be in sync with the GPII/windows master branch that has the new merges which potentially could fix the CI failure.

ok to test

**Comment by amb26** [comment]
The native parts of the build executed at least, but got the diagnostic:
````
default:   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj]
    default: "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper.sln" (default target) (1) ->
    default: "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj" (default target) (2) ->
    default: (ResolveAssemblyReferences target) -> 
    default:   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj]
    default:   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj]
````
 - does this mean that gpii-app is executing against the wrong VM?

**Comment by cindyli** [comment]
The rename of a model path (activeContextName -> activePrefsSetName) fixed the test failure of the tooltip label at keyin.

The new failure is:
```
13:18:50.872:  jq: FAIL: Module "GPII service tests" Test name "Test window service" - Message: Service tests should pass
13:18:50.872:  jq: Expected: 0
13:18:50.872:  jq: Actual: 1
```

Seems resulted from a missing module required by gpii-service:
```
13:18:50.842:  FATAL ERROR: Uncaught exception: The specified module could not be found.
\\?\UNC\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\node_modules\ref-napi\build\Release\binding.node
Error: The specified module could not be found.
```
